### ISSUE TITLE
Bullseye

### ISSUE THREAD

**Issue by schaecsn** [daniel-thompson/pinebook-pro-debian-installer#12]
Why do you default to bullseye?

Personal preference or does it include packages tuned to Pinebook Pro?

**Comment by daniel-thompson** [comment]
buster does not have a recent enough panfrost driver.

BTW as mentioned in https://github.com/daniel-thompson/pinebook-pro-debian-installer#support please use the Pine64 forum rather than the issue tracker for support questions. The issue tracker is only for problems with the installer or kernel.
