### ISSUE TITLE
DM_CRYPT is enabled in factory default operating system

### ISSUE THREAD

**Issue by schaecsn** [daniel-thompson/pinebook-pro-debian-installer#13]
The factory default operating system includes DM_CRYPT kernel option since version 4.4.210 - see here for the vanilla 4.4.210 .config http://students.engr.scu.edu/~sschaeck/misc/pinebookpro-config-4.4.210.txt

You may want to clarify in the README file that an updated factory debian is enough for bootstrapping disk encryption.

**Comment by daniel-thompson** [comment]
I'll take a look next time I'm doing an update. In the mean time pull requests are welcome (you can edit directly on github by clicking on README.md and using the pencil icon).

**Comment by develroo** [comment]
Can confirm. Got my PBP a few weeks back and the latest updates include cryptsetup

For reference:

```
cat /etc/os-release 
NAME="Manjaro-ARM"
ID=manjaro-arm
ID_LIKE=manjaro,arch
PRETTY_NAME="Manjaro ARM"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/c/manjaro-arm/"

```
```
uname -a
Linux pinebookp 5.7.0-3-MANJARO-ARM #1 SMP Sun Jul 5 18:30:55 UTC 2020 aarch64 GNU/Linux

```
```
cryptsetup --version
cryptsetup 2.3.3

```
