### ISSUE TITLE
It doesn't work when using manjaro

### ISSUE THREAD

**Issue by e-minguez** [daniel-thompson/pinebook-pro-debian-installer#16]
Basically apt-get install cryptsetup debootstrap pigz doesn't work.
Also, Manjaro doesn't have /usr/sbin in the path so some commands fail (the first one is adduser)
I'll try to do a PR to fix it, it is just a matter of using pacman if running in Manjaro and setting a proper $PATH env var.

**Comment by daniel-thompson** [comment]
I'm inclined to close this at this point. I've not objections to (nice) patches to add support for bootstraping from other distro but equally the current README does say that the installer is expected to run on Debian or Ubuntu.
