### ISSUE TITLE
Window manager

### ISSUE THREAD

**Issue by FatBirdie** [daniel-thompson/pinebook-pro-debian-installer#20]
Only the Gnome window manager can be installed at this moment.
Other window managers gets stuck in a loop, going into graphical mode, the mouse pointer shows, reverts back to text and repeats this over and over.

Installing other window manager than Gnome after installation works, but crashes as soon as ctrl/alt/right touchpad buton is clicked (and probably more).

**Comment by daniel-thompson** [comment]
This doesn't look like it is a bug in the installer itself. It is much more likely to be a problem with the graphics libraries (which are part of Debian, not part of this installer). As it happens, a new graphics driver was integrated into Debian Bullseye earlier this week which may help.
