### ISSUE TITLE
How to resolve error: "E: Unable to execute target architecture ""

### ISSUE THREAD

**Issue by shafiquejamal** [daniel-thompson/pinebook-pro-debian-installer#26]
Please excuse my if this is not the correct forum for my issue. I am running Debian 10 on my non-Pinebook Pro, and on this machine I am runing the `pinebook-pro-debian-installer`. I tried to create an image on an SD card using the following command:

```
sudo ./install-debian BLKDEV=/dev/sdb 
```

This results in the following error:

```
...
Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   



>>>> Mounting target filesystem



>>>> Installing base system

E: Unable to execute target architecture


>>>> umount

umount: /home/sjamal/Downloads/pinebook-pro-debian-installer/sysimage/dev: no mount point specified.
umount: /home/sjamal/Downloads/pinebook-pro-debian-installer/sysimage/proc: no mount point specified.
umount: /home/sjamal/Downloads/pinebook-pro-debian-installer/sysimage/sys: no mount point specified.
```

The installer does write to the flashcard, but when I stick the flashcard into the Pinebook Pro and turn it on, the PBP does not boot from the flashcard. Is there an issue with the installer, or am I doing something wrong?

Thanks,

**Comment by e-minguez** [comment]
The script is intended to be executed in the pinebook pro directly.
