### ISSUE TITLE
Update mr_fixit submodule

### ISSUE THREAD

**Issue by e-minguez** [daniel-thompson/pinebook-pro-debian-installer#3]
It looks like there is a v1.7 branch in mrfixit [repo](https://github.com/mrfixit2001/updates_repo/tree/v1.7)
I'm not sure about the changes (the repository is very difficult to track...) but just in case.
Thanks!

**Comment by daniel-thompson** [comment]
Tracking changes to the update repo involves looking at the [filesystem directory](https://github.com/mrfixit2001/updates_repo/tree/v1.7/pinebook/filesystem) and seeing when idbloader.img, uboot.img and trust.img have been changed recently.

We only need to update if these files have been changed (so I think we are good for now).
