### ISSUE TITLE
Mobian installer

### ISSUE THREAD

**Issue by FedericoCeratto** [daniel-thompson/pinebook-pro-debian-installer#32]
Hello Daniel,
FYI I've been putting together a simple installer for Mobian on PinePhone: https://salsa.debian.org/Mobian-team/mobian-installer

**Comment by daniel-thompson** [comment]
As mentioned in [the roadmap](https://github.com/daniel-thompson/pinebook-pro-debian-installer#roadmap) the long term "goal" for this repo is to be obsoleted by the full Debian installer.
