### ISSUE TITLE
External display not recognized

### ISSUE THREAD

**Issue by kgrossjo** [daniel-thompson/pinebook-pro-debian-installer#5]
I just received my Pinebook Pro on New Year's Eve, so I spent some time playing around.  I've got an external 4k display with an HDMI-to-USB-C adapter.  With the standard Debian 9 MATE image, this works, though the external display is driven with 1920x1080 only.  But with Debian buster installed using this installer, the external display remains dark.

I'm using gdm3 for logging in, and mostly running Gnome on Wayland, but I briefly tried Gnome on Xorg as well as XFCE, and for all of them the external display remained dark.

When going to the display settings, there is only one display listed -- the internal display.

**Comment by daniel-thompson** [comment]
When USB3 support was enabled I believe it resulted in the USB type C connector no longer being revisible so be sure to try it both ways up.

**Comment by kgrossjo** [comment]
I have now tried to enter the USB type C plug both ways, i.e. both sides up.  Neither of them work.  I made sure that the display is on and switched to HDMI-2 input (which is what this cable is connected to), and I looked at the Gnome settings panel for the displays, the display was not listed there.  Also I tried Sway and used "swaymsg -pt get_outputs" which only listed the internal display.

Do I need to boot with the display connected?  It is not required on  my MacBooks so it didn't occur to me to try that, I just thought of this aspect while writing this comment.

Another potentially relevant factoid is that this is an HDMI cable with an HDMI-to-USB-C adapter attached.  This very same cable with the very same adapter works well with my Macbook and it also works with the stock Debian 9 MATE build on the eMMC.  (I believe it worked with the factory one, but I since flashed a new revision and I don't quite remember the sequence of events, it could be that I've only tried the newer version.)

**Comment by kgrossjo** [comment]
I've now gone through the entire forum thread on the installer, and found a cross reference to another thread about USB-C docks (https://forum.pine64.org/showthread.php?tid=7802&page=5) and a link to the wiki (https://wiki.pine64.org/index.php/Pinebook_Pro#USB_docks_.26_USB_C_alternate_mode_video).  I guess it's possible my adapter is one that doesn't work because it offers USB-C, USB-A and HDMI inputs.  (But why is it working with the stock Debian 9?)  But the Wiki doesn't explain enough for me to understand what I need to buy.  Maybe I will wait for an adapter to appear on the store...

**Comment by schanzen** [comment]
I can confirm this and it is really puzzling. dmesg output shows that a "rockchip/dptx.bin" fails to load (error -2). It tries 3 times then times out.

**Comment by schanzen** [comment]
I have now manually updated the firmware submodule. It pulled the dptx.bin. Reinstalling to SD now .

**Comment by schanzen** [comment]
I can confirm that copying the firmware file "rockchip/dptx.bin" from https://gitlab.manjaro.org/tsys/pinebook-firmware directly into /lib/firmware of the installation (RootFS) makes USB-C displays work for me :) @daniel-thompson you might want to update the firmware submodule and add to the installer script that the rockchip firmware folder is also copied.
