### ISSUE TITLE
Does it work to upgrade to unstable?

### ISSUE THREAD

**Issue by kgrossjo** [daniel-thompson/pinebook-pro-debian-installer#6]
I was wondering if it works to install Bullseye using this script and then to upgrade to Sid?  The README briefly talks about a custom kernel, so perhaps I need to install my own kernel?

Edit: Corrected typo, I meant bullseye and not buster.

**Comment by kgrossjo** [comment]
I see that you have a `Debian_Testing` folder at OpenSuse, which is where the kernel comes from, and you also have an unstable folder there.  So with a little bit of luck, it will suffice to change `sources.list` and `sources.list.d/*` to point to unstable.  But I will wait for confirmation.

**Comment by daniel-thompson** [comment]
Please put questions on the forum topic. They will get a bigger audience there (and there is more scope for other users to help answer such questions).

FWIW there's no reason this shouldn't work but I've not seen any success report on the forum from someone that has tried it (which is the other reason it is better to discuss on the forum... success reports are also easier for others to find).
