### ISSUE TITLE
device-mapper: reload ioctl on mmcblk0-RootFS failed: Invalid argument

### ISSUE THREAD

**Issue by rillian** [daniel-thompson/pinebook-pro-debian-installer#8]
Hi. Thanks for making this installer!

I got my Pinebook Pro on Friday and tried the installer today with a new sd card. The card mounted as mmcblk0, so the default instructions didn't work. Overriding with `BLKDEV` it then [failed mounting the target filesystem](https://hastebin.com/gecebinuli.sql):

```
This will overwrite data on /dev/mmcblk0p6 irrevocably.

Are you sure? (Type uppercase yes): YES
Enter passphrase: 
Verify passphrase: 
Enter passphrase for /dev/mmcblk0p6: 
device-mapper: reload ioctl on mmcblk0-RootFS failed: Invalid argument
```

At least, I assume the first two passphrase prompts are to set up the crypt device and the third is to decrypt it for mounting?

Happy to troubleshoot if you have any suggestions for what to try...

**Comment by rillian** [comment]
I get the same error from the automounter after removing and re-inserting the card. Maybe something missing in the host kernel?

**Comment by rillian** [comment]
journalctl says
```
Jan 12 17:35:57 Debian-Desktop kernel: device-mapper: table: 252:0: crypt: unknown target type
Jan 12 17:35:57 Debian-Desktop kernel: device-mapper: ioctl: error adding target to table
```

**Comment by daniel-thompson** [comment]
Installing with CRYPT=y requires your kernel to support filesystem encryption. There is a note in the README to remind you that if your current distro does not support filesystem encryption then you can make a temporary unencrypted install with the installer and then use that OS to do an encrypted install (at least you can if you have two SD cards and a USB SD card reader).

I assume you are using the default Debian Stretch OS? If so then I think someone already filed this issue on that tracker: https://github.com/mrfixit2001/debian_desktop/issues

**Comment by e-minguez** [comment]
https://github.com/mrfixit2001/debian_desktop/issues/24
